{% set name = "typhon" %}
{% set version = "0.11.0dev" %}
{% set dev_url = "https://github.com/atmtools/typhon" %}

package:
  name: {{ name|lower }}
  version:  {{ version }}

source:
  # url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  # url: "https://test.pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  # url: https://github.com/atmtools/typhon/releases/download/{{ version }}/typhon-{{ version }}.tar.gz
  git_url: {{ dev_url }}.git
  git_depth: 1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools >=3.4
  run:
    - python
    - docutils
    - fsspec!=2023.12.0,!=2023.12.1,!=2024.3.1
    - h5netcdf
    - imageio
    - matplotlib>=1.4
    - netcdf4>=1.1.1
    - numexpr
    - numpy>=2
    - pandas
    - scikit-image
    - scikit-learn
    - scipy>=1.6
    - setuptools>=0.7.2
    - xarray>=0.10.2

test:
  imports:
    - typhon

about:
  home: {{ dev_url }}
  license: MIT
  license_file: LICENSE
  summary: "Typhon is a collection of tools for atmospheric research."

extra:
  recipe-maintainers:
    - olemke
