name: Test

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}-py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu, windows, macos]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

        include:
          - name: ubuntu
            os: ubuntu-latest

          - name: windows
            os: windows-latest

          - name: macos
            os: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: typhon
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
      - shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Lint with flake8 (Linux)
        if: runner.os == 'Linux' && matrix.python-version == '3.8'
        continue-on-error: true
        shell: bash -el {0}
        run: |
          pip install flake8
          flake8 . --statistics || echo "::error::Check flake8 output for errors"

      - name: Testfiles Setup
        shell: bash -el {0}
        run: |
          git clone --depth=1 https://github.com/atmtools/typhon-testfiles.git

      - name: Test
        shell: bash -el {0}
        run: |
          export TYPHONTESTFILES=$PWD/typhon-testfiles
          pytest --pyargs typhon
